# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: develop # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
    - JAVASCRIPT_ES
    - COPYPASTE_JSCPD
    - EDITORCONFIG_EDITORCONFIG_CHECKER
    - YAML_YAMLLINT
    - SPELL_MISSPELL
    - HTML_HTMLHINT
    - GIT_GIT_DIFF
    - CREDENTIALS_SECRETLINT
    - JSON_JSONLINT
# DISABLE:
    # - COPYPASTE # Uncomment to disable checks of abusive copy-pastes
    # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRE_COMMANDS:
    -
        command: npm install "babel-preset-react-app@^10.0.0" "@babel/eslint-parser@^7.15.7"
        cwd: workspace # Will be run at the root of the workspace (usually your repository root)
